import Project from "@/components/ProjectComp/Project";
import { ALL_PROJECTS } from "@/services/graphql/queries";
import { getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";

export default function ProjectPage({ projects, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Project projects={projects} accessToken={accessToken} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    accessToken = token;
  } catch (err) {
    accessToken = null;
  }

  const { data } = await client.query({
    query: ALL_PROJECTS,
  });

  return {
    props: {
      projects: data?.listProject || [],
      accessToken: accessToken,
    },
  };
}
