import Login from "@/components/LoginComp/Login";
import { getCookie } from "@/services/utils/cookieExtract";
import Head from "next/head";

export default function LoginPage({ accessToken, userIP }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login accessToken={accessToken} userIP={userIP} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    accessToken = token;
  } catch (err) {
    accessToken = null;
  }
  // setting private route
  if (accessToken) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }

  const url = "https://api.db-ip.com/v2/free/self";
  const data = await fetch(url);
  const resData = await data.json();

  return {
    props: {
      userIP: resData,
      accessToken: accessToken,
    },
  };
}
