import Login from "@/components/LoginComp/Login";
import Head from "next/head";

export default function LoginPage() {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login />
      </main>
    </div>
  );
}
