import Register from "@/components/LoginComp/Register";
import Head from "next/head";

export default function RegisterPage() {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register />
      </main>
    </div>
  );
}
