import AddProjectComponent from "@/components/DashboardComp/AddProjectComp";
import Head from "next/head";

export default function AddProject() {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Add Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AddProjectComponent />
      </main>
    </div>
  );
}
