import Profile from "@/components/ProfileComp/Profile";
import { GET_USER } from "@/services/graphql/queries";
import { extractJWT, getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";

export default function ProfilePage({ user, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Profile tokenData={user} accessToken={accessToken} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    const decodedToken = extractJWT(token);
    accessToken = decodedToken;
  } catch (err) {
    accessToken = null;
  }
  // setting private route
  if (!accessToken) {
    ctx.res.setHeader("Set-Cookie", "portfolio_2_0=; path=/; max-age=0");
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const { data } = await client.query({
    query: GET_USER,
    variables: {
      input: accessToken?.userId,
    },
    update: (cache) => {
      cache.evict({ fieldName: "avatar" });
    },
  });

  return {
    props: {
      user: data?.getUser || null,
      accessToken: accessToken,
    },
  };
}
