import About from "@/components/AboutComp/About";
import { getCookie } from "@/services/utils/cookieExtract";
import Head from "next/head";

export default function AboutPage({ accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <About accessToken={accessToken} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    accessToken = token;
  } catch (err) {
    accessToken = null;
  }

  return {
    props: {
      accessToken: accessToken,
    },
  };
}
