import { ALL_BLOGS, ALL_PROJECTS } from "@/services/graphql/queries";
import { getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";
import HomePage from "./home/HomePage";

export default function DefaultPage({ projects, blogs, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage projects={projects} blogs={blogs} accessToken={accessToken} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    accessToken = token;
  } catch (err) {
    accessToken = null;
  }

  const data1 = await client.query({
    query: ALL_PROJECTS,
  });

  const data2 = await client.query({
    query: ALL_BLOGS,
  });

  return {
    props: {
      projects: data1?.data?.listProject || [],
      blogs: data2?.data?.listBlog || [],
      accessToken: accessToken,
    },
  };
}
