import Head from "next/head";
import HomePage from "./home/HomePage";

export default function Home() {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage />
      </main>
    </div>
  );
}
