import Blog from "@/components/BlogComp/Blog";
import { ALL_BLOGS } from "@/services/graphql/queries";
import { getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";

export default function BlogPage({ blogs, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Blog blogs={blogs} accessToken={accessToken} />
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { cookie } = ctx.req.headers;
  let accessToken = null;
  try {
    const token = getCookie("portfolio_2_0", cookie);
    accessToken = token;
  } catch (err) {
    accessToken = null;
  }

  const { data } = await client.query({
    query: ALL_BLOGS,
  });

  return {
    props: {
      blogs: data?.listBlog || [],
      accessToken: accessToken,
    },
  };
}
