import AddBlogComponent from "@/components/DashboardComp/BlogComp/AddBlogComponent";
import { ALL_CATEGORIES_NAME, ALL_TAGS_NAME } from "@/services/graphql/queries";
import { getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";

export default function AddBlogPage({ tags, categories, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Add Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AddBlogComponent
          tags={tags}
          categories={categories}
          accessToken={accessToken}
        />
      </main>
    </div>
  );
}

// to get new added categories and tags from the database we should use getServerSideProps
export async function getServerSideProps({ req, res }) {
  const { cookie } = req.headers;
  const accessToken = getCookie("portfolio_2_0", cookie);

  // setting private route
  if (!accessToken) {
    res.setHeader("Set-Cookie", "portfolio_2_0=; path=/; max-age=0");
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const tagData = await client.query({
    query: ALL_TAGS_NAME,
  });

  const categoryData = await client.query({
    query: ALL_CATEGORIES_NAME,
  });

  return {
    props: {
      tags: tagData?.data?.listTag || [],
      categories: categoryData?.data?.listCategory || [],
      accessToken: accessToken || "",
    },
  };
}
