import Head from "next/head";
import DashboardPage from "./DashboardPage";

export default function Dashboard() {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardPage />
      </main>
    </div>
  );
}
