import { ALL_CATEGORIES_NAME } from "@/services/graphql/queries";
import client from "apollo-client";
import Head from "next/head";
import DashboardPage from "./DashboardPage";

export default function Dashboard({ categories }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardPage categories={categories} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: ALL_CATEGORIES_NAME,
  });

  return {
    props: {
      categories: data?.listCategory || [],
    },
  };
}
