import UsersComponent from "@/components/DashboardComp/UsersComp/UsersComponent";
import { ALL_USERS } from "@/services/graphql/queries";
import { extractJWT, getCookie } from "@/services/utils/cookieExtract";
import client from "apollo-client";
import Head from "next/head";

export default function UsersPage({ users, userDetails, accessToken }) {
  return (
    <div className="page_wrapper">
      <Head>
        <title>Portfolio - Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <UsersComponent
          userDetails={userDetails}
          initUsers={users}
          accessToken={accessToken}
        />
      </main>
    </div>
  );
}

// to get new added categories and tags from the database we should use getServerSideProps
export async function getServerSideProps({ req, res }) {
  const { cookie } = req.headers;
  const accessToken = getCookie("portfolio_2_0", cookie);

  // setting private route
  if (!accessToken) {
    res.setHeader("Set-Cookie", "portfolio_2_0=; path=/; max-age=0");
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const userDetails = extractJWT(accessToken);

  const { data } = await client.query({
    query: ALL_USERS,
  });

  return {
    props: {
      userDetails: userDetails || {},
      users: data?.listUser || [],
      accessToken: accessToken || "",
    },
  };
}
